import { useState } from "react";
import JSZip from "jszip";
import {
  ChevronRight,
  ChevronLeft,
  Plus,
  Trash2,
  AlertTriangle,
  Download,
  CheckCircle,
  Wand2,
} from "lucide-react";
import { Button } from "@/components/ui/button";

// ─── Types ────────────────────────────────────────────────────────────────────

interface Action {
  name: string;
  description: string;
  consequential: boolean;
  reversible: "yes" | "no" | "partially";
}

interface Approver {
  clientRoleName: string;
  authorityClass: string;
}

interface WizardState {
  // Step 1
  workflowName: string;
  workflowDescription: string;
  workflowFrequency: string;
  workflowEnvironment: string;
  workflowSector: string;
  // Step 2
  actions: Action[];
  // Step 3
  aiOutput: string;
  aiModel: string;
  aiHosting: string;
  aiSelfApproval: string;
  // Step 4
  approvers: Approver[];
  // Step 5
  deploymentMode: string;
}

const INITIAL_STATE: WizardState = {
  workflowName: "",
  workflowDescription: "",
  workflowFrequency: "",
  workflowEnvironment: "",
  workflowSector: "",
  actions: [{ name: "", description: "", consequential: true, reversible: "no" }],
  aiOutput: "",
  aiModel: "",
  aiHosting: "",
  aiSelfApproval: "",
  approvers: [{ clientRoleName: "", authorityClass: "" }],
  deploymentMode: "",
};

// ─── Authority classes ────────────────────────────────────────────────────────

const AUTHORITY_CLASSES = [
  { value: "senior_analyst", label: "Senior Analyst", desc: "An experienced analyst who reviews and approves AI-proposed actions" },
  { value: "compliance_officer", label: "Compliance Officer", desc: "A compliance professional responsible for regulatory oversight" },
  { value: "operations_manager", label: "Operations Manager", desc: "An operations manager with authority over workflow decisions" },
  { value: "system", label: "System", desc: "A trusted automated system (not AI) that can authorize actions" },
  { value: "human", label: "Human (General)", desc: "A general human actor (use if none of the above fit)" },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toSnakeCase(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

// ─── File generators ──────────────────────────────────────────────────────────

function generatePolicyJson(s: WizardState): string {
  const workflowClass = toSnakeCase(s.workflowName) || "unnamed_workflow";

  const actorMappings: Record<string, string> = {};
  for (const ap of s.approvers) {
    if (ap.clientRoleName && ap.authorityClass) {
      actorMappings[ap.clientRoleName] = ap.authorityClass;
    }
  }

  const approverClasses = s.approvers
    .filter((ap) => ap.authorityClass)
    .map((ap) => ap.authorityClass);

  const actionPolicies: Record<string, Record<string, string>> = {};
  const workflowActions: Record<string, string> = {};
  for (const action of s.actions) {
    if (action.name) {
      const ac = toSnakeCase(action.name);
      workflowActions[ac] = action.consequential ? "requires_approval" : "auto_allow";
    }
  }
  if (Object.keys(workflowActions).length > 0) {
    actionPolicies[workflowClass] = workflowActions;
  }

  const policy: Record<string, unknown> = {
    _schema: "cerbaseal-policy/v1",
    _generated: new Date().toISOString(),
    _workflowName: s.workflowName,
  };

  if (Object.keys(actorMappings).length > 0) {
    policy["actorMappings"] = actorMappings;
  }

  if (approverClasses.length > 0) {
    policy["approvalChains"] = {
      [workflowClass]: [...new Set(approverClasses)],
    };
  }

  if (Object.keys(actionPolicies).length > 0) {
    policy["actionPolicies"] = actionPolicies;
  }

  return JSON.stringify(policy, null, 2);
}

function generatePilotChecklist(s: WizardState): string {
  const workflowClass = toSnakeCase(s.workflowName) || "unnamed_workflow";
  const primaryApprover = s.approvers[0]?.authorityClass || "senior_analyst";
  const primaryRole = s.approvers[0]?.clientRoleName || "approver";
  const firstAction = s.actions[0];
  const firstActionClass = firstAction ? toSnakeCase(firstAction.name) : "action";

  return `# CerbaSeal Pilot Checklist — ${s.workflowName || "Unnamed Workflow"}

_Generated by the CerbaSeal Workflow Mapping Wizard_  
_Workflow class: \`${workflowClass}\`_

---

## Deployment

- [ ] Node.js 18+ installed on target server
- [ ] pnpm installed
- [ ] CerbaSeal-Core cloned and dependencies installed (\`pnpm install\`)
- [ ] pnpm test — 419/419 passing
- [ ] pnpm audit:repo — 16/16 passing
- [ ] pnpm export:proof — stableChecksum confirmed
- [ ] \`cerbaseal.policy.json\` placed at repository root
- [ ] Configuration validated: \`pnpm audit:repo\` still 16/16 with policy file present

---

## Configuration Verification

- [ ] Workflow class \`${workflowClass}\` recognised in gate service
- [ ] Actor mappings confirmed: ${s.approvers.map((ap) => `"${ap.clientRoleName}" → \`${ap.authorityClass}\``).join(", ") || "none configured"}
- [ ] Approval chains verified for \`${workflowClass}\`
- [ ] Action policies verified: ${s.actions.filter((a) => a.name).map((a) => `\`${toSnakeCase(a.name)}\` → ${a.consequential ? "requires_approval" : "auto_allow"}`).join(", ") || "none configured"}

---

## Scenario Testing

- [ ] **REJECT scenario:** AI actor submits \`${firstActionClass}\` for \`${workflowClass}\` — expected outcome: REJECT (AI cannot self-authorize)
- [ ] **HOLD scenario:** \`${firstActionClass}\` submitted for \`${workflowClass}\` without approval artifact — expected outcome: HOLD
- [ ] **ALLOW scenario:** \`${firstActionClass}\` submitted for \`${workflowClass}\` with \`${primaryApprover}\` approval (mapped from "${primaryRole}") — expected outcome: ALLOW

---

## Evidence Verification

- [ ] Evidence bundle generated for each scenario
- [ ] pnpm verify:proof passes after scenarios
- [ ] Audit log contains at minimum 3 entries (one per scenario)
- [ ] Each evidence bundle contains: requestId, finalState, reasonCodes, actorId, timestamp

---

## Deployment Mode

- [ ] **${s.deploymentMode === "mode_a" ? "Mode A (Lamont Labs-hosted)" : s.deploymentMode === "mode_b" ? "Mode B (Partner-hosted)" : s.deploymentMode === "mode_c" ? "Mode C (Client-controlled)" : "Mode not selected"}** deployment confirmed

---

## Training

- [ ] Technical owner has reviewed the Admin Guide
- [ ] Operational reviewers have reviewed the Operator Guide
- [ ] FAQ reviewed by all operational staff
- [ ] Escalation path confirmed: internal first-line → Lamont Labs

---

_Workflow: ${s.workflowName} · Sector: ${s.workflowSector || "Not specified"} · Frequency: ${s.workflowFrequency || "Not specified"}_
`;
}

function generateScenarioTests(s: WizardState): string {
  const workflowClass = toSnakeCase(s.workflowName) || "unnamed_workflow";
  const primaryApprover = s.approvers[0]?.authorityClass || "senior_analyst";
  const firstAction = s.actions[0];
  const firstActionClass = firstAction ? toSnakeCase(firstAction.name) : "action";
  const approverClasses = s.approvers
    .filter((ap) => ap.authorityClass)
    .map((ap) => ap.authorityClass);

  return `/**
 * CerbaSeal Scenario Tests — ${s.workflowName || "Unnamed Workflow"}
 *
 * Generated by the CerbaSeal Workflow Mapping Wizard
 * Workflow class: ${workflowClass}
 *
 * Run with: pnpm test (from CerbaSeal-Core root)
 * Or import into your own test suite.
 */

import { describe, it, expect } from "vitest";
import { ExecutionGateService } from "../src/services/execution/execution-gate-service.js";
import { loadCerbaSealPolicy } from "../src/config/cerbaseal-policy.js";

const policy = loadCerbaSealPolicy();

const gate = new ExecutionGateService(
  { additionalAuthorityClasses: [${approverClasses.map((c) => `"${c}"`).join(", ")}] },
  policy
);

function makeRequest(overrides: Record<string, unknown> = {}) {
  return {
    requestId: \`req_\${Date.now()}_\${Math.random().toString(36).slice(2)}\`,
    workflowClass: "${workflowClass}",
    proposedActionClass: "${firstActionClass}",
    actorId: "actor_001",
    actorAuthorityClass: "${primaryApprover}",
    approvalRequired: false,
    approvalArtifact: undefined,
    provenanceRef: {
      sourceSystem: "pilot-test",
      modelVersion: "${s.aiModel || "unknown"}",
      inputHash: "sha256-test-hash",
    },
    requestedAt: new Date().toISOString(),
    ...overrides,
  };
}

describe("${s.workflowName || "Wizard"} — CerbaSeal Scenario Tests", () => {

  it("REJECT — AI actor cannot self-authorize ${firstActionClass}", () => {
    const req = makeRequest({
      actorAuthorityClass: "ai",
      approvalRequired: false,
    });
    const result = gate.evaluate(req as Parameters<typeof gate.evaluate>[0]);
    expect(result.decisionEnvelope.finalState).toBe("REJECT");
    expect(result.decisionEnvelope.trace.reasonCodes).toContain("AI_SELF_AUTHORIZATION_FORBIDDEN");
  });

  it("HOLD — ${firstActionClass} without approval artifact causes HOLD", () => {
    const req = makeRequest({
      actorAuthorityClass: "${primaryApprover}",
      approvalRequired: true,
      approvalArtifact: undefined,
    });
    const result = gate.evaluate(req as Parameters<typeof gate.evaluate>[0]);
    expect(result.decisionEnvelope.finalState).toBe("HOLD");
    expect(result.decisionEnvelope.humanApprovalRequired).toBe(true);
  });

  it("ALLOW — ${firstActionClass} with valid ${primaryApprover} approval", () => {
    const req = makeRequest({
      actorAuthorityClass: "${primaryApprover}",
      approvalRequired: true,
      approvalArtifact: {
        approvalId: "approval_pilot_001",
        approverId: "approver_001",
        forRequestId: "will-be-overridden",
        approverAuthorityClass: "${primaryApprover}",
        privilegedAuthSatisfied: true,
        immutableSignature: "sig_pilot_001",
        approvedAt: new Date().toISOString(),
      },
    });
    // forRequestId must match requestId
    const approvalArtifact = (req as Record<string, unknown>)["approvalArtifact"] as Record<string, unknown>;
    approvalArtifact["forRequestId"] = req.requestId;

    const result = gate.evaluate(req as Parameters<typeof gate.evaluate>[0]);
    expect(result.decisionEnvelope.finalState).toBe("ALLOW");
  });

${s.actions.slice(1).filter((a) => a.name).map((action) => {
  const ac = toSnakeCase(action.name);
  return `  it("${action.consequential ? "HOLD" : "ALLOW"} — ${ac} action (${action.consequential ? "consequential" : "non-consequential"})", () => {
    const req = makeRequest({
      proposedActionClass: "${ac}",
      approvalRequired: ${action.consequential},
    });
    const result = gate.evaluate(req as Parameters<typeof gate.evaluate>[0]);
    // ${action.consequential ? "Consequential action requires approval — expect HOLD if no artifact" : "Non-consequential action — expect ALLOW"}
    expect(result.decisionEnvelope.finalState).toBe("${action.consequential ? "HOLD" : "ALLOW"}");
  });
`;
}).join("\n")}
});
`;
}

function generateHandoffPack(s: WizardState): string {
  const workflowClass = toSnakeCase(s.workflowName) || "unnamed_workflow";

  return `# CerbaSeal Handoff Pack — ${s.workflowName || "Unnamed Workflow"}

_Generated by the CerbaSeal Workflow Mapping Wizard_  
_Date: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}_

---

## What Was Configured

This package contains the CerbaSeal configuration for the **${s.workflowName || "unnamed"}** workflow.
Hand this document to your technical owner before deployment begins.

---

## Workflow Summary

| Field | Value |
|---|---|
| Workflow name | ${s.workflowName || "—"} |
| Workflow class | \`${workflowClass}\` |
| Description | ${s.workflowDescription || "—"} |
| Frequency | ${s.workflowFrequency || "—"} |
| Environment | ${s.workflowEnvironment || "—"} |
| Sector | ${s.workflowSector || "—"} |

---

## Actions Governed

${s.actions.filter((a) => a.name).map((a, i) => `### Action ${i + 1}: ${a.name}

| Field | Value |
|---|---|
| Action class | \`${toSnakeCase(a.name)}\` |
| Description | ${a.description || "—"} |
| Consequential | ${a.consequential ? "Yes — changes something in the real world" : "No — informational only"} |
| Reversible | ${a.reversible === "yes" ? "Yes" : a.reversible === "no" ? "No" : "Partially"} |
| Policy | ${a.consequential ? "**requires_approval** — human approval mandatory before execution" : "**auto_allow** — may proceed without approval"} |
`).join("\n") || "_No actions configured_\n"}

---

## AI System

| Field | Value |
|---|---|
| What the AI produces | ${s.aiOutput || "—"} |
| Model / system | ${s.aiModel || "—"} |
| Hosting | ${s.aiHosting || "—"} |
| Self-approval flag | ${s.aiSelfApproval === "yes" ? "⚠️ Yes (CerbaSeal will REJECT self-authorization attempts — this is by design)" : s.aiSelfApproval === "no" ? "No" : "Unsure"} |

**Invariant:** CerbaSeal enforces unconditionally that AI actors cannot self-authorize.
Any request where the proposing actor has authority class \`ai\` will receive a REJECT decision.
This cannot be overridden by policy.

---

## Human Approvers

${s.approvers.filter((ap) => ap.clientRoleName && ap.authorityClass).map((ap) => {
  const cls = AUTHORITY_CLASSES.find((c) => c.value === ap.authorityClass);
  return `- **${ap.clientRoleName}** → CerbaSeal class \`${ap.authorityClass}\` (${cls?.desc || ap.authorityClass})`;
}).join("\n") || "_No approvers configured_"}

These mappings are declared in \`cerbaseal.policy.json\` under \`actorMappings\`.
When a request arrives with an actor identified as one of these roles, CerbaSeal
translates it to the mapped authority class before evaluation.

---

## Deployment Mode

${s.deploymentMode === "mode_a"
  ? "**Mode A — Lamont Labs-hosted**\n\nCerbaSeal runs on Lamont Labs infrastructure. Lamont Labs manages uptime, updates, and infrastructure. Your team integrates via API. Data residency is Lamont Labs default region."
  : s.deploymentMode === "mode_b"
  ? "**Mode B — Partner-hosted**\n\nCerbaSeal is deployed and managed by a certified consulting partner. Your team works with the partner for configuration, updates, and support escalation."
  : s.deploymentMode === "mode_c"
  ? "**Mode C — Client-controlled**\n\nCerbaSeal runs on your own infrastructure. Your technical team owns deployment, updates, and infrastructure. Full data residency control. Requires Node.js 18+ and pnpm."
  : "_No deployment mode selected_"}

---

## Files in This Package

| File | Purpose |
|---|---|
| \`cerbaseal.policy.json\` | CerbaSeal policy configuration — place at repository root |
| \`pilot-checklist.md\` | Step-by-step deployment and verification checklist |
| \`scenario-tests.ts\` | Runnable TypeScript test scenarios for ALLOW / HOLD / REJECT |
| \`handoff-pack.md\` | This document — overview for the technical owner |

---

## What to Verify Before Go-Live

1. **Run \`pnpm test\`** — all 419 tests must pass
2. **Run \`pnpm audit:repo\`** — all 16 checks must pass, including check 16 (policy file validation)
3. **Run the three scenario tests** — REJECT, HOLD, and ALLOW must all produce expected outcomes
4. **Review evidence bundles** — each scenario should produce a timestamped, signed evidence record
5. **Confirm actor mappings** — send a test request using each configured role name and verify the translation

---

## Contacts

- **CerbaSeal support:** Lamont Labs — via your partner or pilot agreement
- **Technical documentation:** See \`docs/\` in CerbaSeal-Core
- **Admin guide:** \`docs/client-adoption/training/admin-guide.md\`
- **FAQ:** \`docs/client-adoption/training/faq.md\`

---

_This package was generated automatically. All configuration values reflect the answers
provided during the wizard session. Review all files before deployment._
`;
}

// ─── Zip download ─────────────────────────────────────────────────────────────

async function downloadConfigPackage(s: WizardState) {
  const zip = new JSZip();
  zip.file("cerbaseal.policy.json", generatePolicyJson(s));
  zip.file("pilot-checklist.md", generatePilotChecklist(s));
  zip.file("scenario-tests.ts", generateScenarioTests(s));
  zip.file("handoff-pack.md", generateHandoffPack(s));

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const slug = toSnakeCase(s.workflowName) || "cerbaseal";
  a.download = `cerbaseal-config-${slug}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Step components ──────────────────────────────────────────────────────────

function FieldLabel({ children }: { children: React.ReactNode }) {
  return <label className="block text-sm font-medium text-slate-300 mb-1.5">{children}</label>;
}

function TextInput({ value, onChange, placeholder, maxLength }: {
  value: string; onChange: (v: string) => void; placeholder?: string; maxLength?: number;
}) {
  return (
    <input
      type="text"
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      maxLength={maxLength}
      className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2.5 text-white text-sm placeholder-slate-500 focus:outline-none focus:border-blue-500 transition-colors"
    />
  );
}

function TextArea({ value, onChange, placeholder, maxLength }: {
  value: string; onChange: (v: string) => void; placeholder?: string; maxLength?: number;
}) {
  return (
    <textarea
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      maxLength={maxLength}
      rows={3}
      className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2.5 text-white text-sm placeholder-slate-500 focus:outline-none focus:border-blue-500 transition-colors resize-none"
    />
  );
}

function SelectInput({ value, onChange, options, placeholder }: {
  value: string; onChange: (v: string) => void; options: { value: string; label: string }[]; placeholder?: string;
}) {
  return (
    <select
      value={value}
      onChange={(e) => onChange(e.target.value)}
      className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-blue-500 transition-colors text-white"
    >
      {placeholder && <option value="" className="text-slate-500">{placeholder}</option>}
      {options.map((o) => (
        <option key={o.value} value={o.value} className="text-white bg-slate-800">{o.label}</option>
      ))}
    </select>
  );
}

function RadioCards({ value, onChange, options }: {
  value: string;
  onChange: (v: string) => void;
  options: { value: string; label: string; desc?: string }[];
}) {
  return (
    <div className="space-y-2">
      {options.map((o) => (
        <button
          key={o.value}
          type="button"
          onClick={() => onChange(o.value)}
          className={`w-full text-left px-4 py-3 rounded-lg border text-sm transition-all ${
            value === o.value
              ? "border-blue-500 bg-blue-950 text-white"
              : "border-slate-700 bg-slate-800 text-slate-300 hover:border-slate-600"
          }`}
        >
          <div className="font-medium">{o.label}</div>
          {o.desc && <div className="text-xs text-slate-400 mt-0.5">{o.desc}</div>}
        </button>
      ))}
    </div>
  );
}

// ─── Step 1: Workflow ─────────────────────────────────────────────────────────

function Step1({ state, update }: { state: WizardState; update: (p: Partial<WizardState>) => void }) {
  return (
    <div className="space-y-5">
      <div>
        <FieldLabel>Workflow name <span className="text-red-400">*</span></FieldLabel>
        <TextInput
          value={state.workflowName}
          onChange={(v) => update({ workflowName: v })}
          placeholder="e.g. Transaction Fraud Review"
          maxLength={100}
        />
        <p className="text-slate-500 text-xs mt-1">Max 100 characters. Will become the workflow class identifier.</p>
        {state.workflowName && (
          <p className="text-slate-400 text-xs mt-1">
            Workflow class: <code className="text-blue-400">{toSnakeCase(state.workflowName) || "…"}</code>
          </p>
        )}
      </div>

      <div>
        <FieldLabel>What does this workflow do? <span className="text-red-400">*</span></FieldLabel>
        <TextArea
          value={state.workflowDescription}
          onChange={(v) => update({ workflowDescription: v })}
          placeholder="Describe what this workflow does in 1–3 sentences."
          maxLength={500}
        />
        <p className="text-slate-500 text-xs mt-1">{state.workflowDescription.length}/500 characters</p>
      </div>

      <div>
        <FieldLabel>How often does this workflow run? <span className="text-red-400">*</span></FieldLabel>
        <SelectInput
          value={state.workflowFrequency}
          onChange={(v) => update({ workflowFrequency: v })}
          placeholder="Select frequency…"
          options={[
            { value: "Continuously", label: "Continuously" },
            { value: "Hourly", label: "Hourly" },
            { value: "Daily", label: "Daily" },
            { value: "Weekly", label: "Weekly" },
            { value: "On-demand", label: "On-demand" },
          ]}
        />
      </div>

      <div>
        <FieldLabel>Current status <span className="text-red-400">*</span></FieldLabel>
        <RadioCards
          value={state.workflowEnvironment}
          onChange={(v) => update({ workflowEnvironment: v })}
          options={[
            { value: "Production", label: "Production", desc: "This workflow is live and running on real data" },
            { value: "Testing", label: "Testing", desc: "Running in a test or staging environment" },
            { value: "Planning", label: "Planning", desc: "Not yet deployed — planning stage" },
          ]}
        />
      </div>

      <div>
        <FieldLabel>Industry or sector <span className="text-red-400">*</span></FieldLabel>
        <SelectInput
          value={state.workflowSector}
          onChange={(v) => update({ workflowSector: v })}
          placeholder="Select sector…"
          options={[
            { value: "Financial services", label: "Financial services" },
            { value: "Healthcare", label: "Healthcare" },
            { value: "Legal", label: "Legal" },
            { value: "Technology", label: "Technology" },
            { value: "Impact / NGO", label: "Impact / NGO" },
            { value: "Other", label: "Other" },
          ]}
        />
      </div>
    </div>
  );
}

// ─── Step 2: Actions ──────────────────────────────────────────────────────────

function Step2({ state, update }: { state: WizardState; update: (p: Partial<WizardState>) => void }) {
  function updateAction(i: number, patch: Partial<Action>) {
    const next = state.actions.map((a, idx) => (idx === i ? { ...a, ...patch } : a));
    update({ actions: next });
  }

  function addAction() {
    if (state.actions.length < 5) {
      update({ actions: [...state.actions, { name: "", description: "", consequential: true, reversible: "no" }] });
    }
  }

  function removeAction(i: number) {
    if (state.actions.length > 1) {
      update({ actions: state.actions.filter((_, idx) => idx !== i) });
    }
  }

  return (
    <div className="space-y-5">
      <div className="bg-slate-800/50 border border-slate-700 rounded-lg p-4 text-sm text-slate-300">
        List the actions your AI system can propose. Examples: "escalate for review", "freeze account", "approve transaction", "send alert".
      </div>

      {state.actions.map((action, i) => (
        <div key={i} className="bg-slate-900 border border-slate-700 rounded-xl p-5">
          <div className="flex items-center justify-between mb-4">
            <span className="text-white font-medium text-sm">Action {i + 1}</span>
            {state.actions.length > 1 && (
              <button
                type="button"
                onClick={() => removeAction(i)}
                className="text-slate-500 hover:text-red-400 transition-colors"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            )}
          </div>

          <div className="space-y-4">
            <div>
              <FieldLabel>Action name <span className="text-red-400">*</span></FieldLabel>
              <TextInput
                value={action.name}
                onChange={(v) => updateAction(i, { name: v })}
                placeholder="e.g. Escalate for review"
              />
              {action.name && (
                <p className="text-slate-400 text-xs mt-1">
                  Action class: <code className="text-blue-400">{toSnakeCase(action.name)}</code>
                </p>
              )}
            </div>

            <div>
              <FieldLabel>Description (optional)</FieldLabel>
              <TextInput
                value={action.description}
                onChange={(v) => updateAction(i, { description: v })}
                placeholder="Brief description of what this action does"
              />
            </div>

            <div>
              <FieldLabel>Is this action consequential? <span className="text-red-400">*</span></FieldLabel>
              <p className="text-slate-500 text-xs mb-2">A consequential action changes something real — a financial record, customer status, or operational state. If in doubt, treat it as consequential.</p>
              <div className="flex gap-3">
                {[true, false].map((v) => (
                  <button
                    key={String(v)}
                    type="button"
                    onClick={() => updateAction(i, { consequential: v })}
                    className={`flex-1 py-2.5 rounded-lg border text-sm font-medium transition-all ${
                      action.consequential === v
                        ? "border-blue-500 bg-blue-950 text-blue-300"
                        : "border-slate-700 bg-slate-800 text-slate-400 hover:border-slate-600"
                    }`}
                  >
                    {v ? "Yes — consequential" : "No — informational"}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <FieldLabel>Can it be reversed? <span className="text-red-400">*</span></FieldLabel>
              <div className="flex gap-2">
                {(["yes", "no", "partially"] as const).map((v) => (
                  <button
                    key={v}
                    type="button"
                    onClick={() => updateAction(i, { reversible: v })}
                    className={`flex-1 py-2.5 rounded-lg border text-sm font-medium transition-all capitalize ${
                      action.reversible === v
                        ? "border-blue-500 bg-blue-950 text-blue-300"
                        : "border-slate-700 bg-slate-800 text-slate-400 hover:border-slate-600"
                    }`}
                  >
                    {v}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>
      ))}

      {state.actions.length < 5 && (
        <button
          type="button"
          onClick={addAction}
          className="w-full border border-dashed border-slate-600 rounded-xl py-3 text-slate-400 hover:text-slate-300 hover:border-slate-500 transition-colors text-sm flex items-center justify-center gap-2"
        >
          <Plus className="w-4 h-4" /> Add another action ({state.actions.length}/5)
        </button>
      )}
    </div>
  );
}

// ─── Step 3: AI Role ──────────────────────────────────────────────────────────

function Step3({ state, update }: { state: WizardState; update: (p: Partial<WizardState>) => void }) {
  return (
    <div className="space-y-5">
      <div>
        <FieldLabel>What does your AI system produce? <span className="text-red-400">*</span></FieldLabel>
        <TextInput
          value={state.aiOutput}
          onChange={(v) => update({ aiOutput: v })}
          placeholder="e.g. a fraud risk score, a ranked list of recommendations"
        />
      </div>

      <div>
        <FieldLabel>AI model or system name (optional)</FieldLabel>
        <TextInput
          value={state.aiModel}
          onChange={(v) => update({ aiModel: v })}
          placeholder="e.g. GPT-4o, internal risk model v3, Claude 3.5"
        />
      </div>

      <div>
        <FieldLabel>Where is the AI model hosted? <span className="text-red-400">*</span></FieldLabel>
        <SelectInput
          value={state.aiHosting}
          onChange={(v) => update({ aiHosting: v })}
          placeholder="Select hosting…"
          options={[
            { value: "Our own infrastructure", label: "Our own infrastructure" },
            { value: "Cloud provider", label: "Cloud provider (AWS, Azure, GCP)" },
            { value: "Third-party API", label: "Third-party API (OpenAI, Anthropic, etc.)" },
            { value: "Unknown", label: "Unknown" },
          ]}
        />
      </div>

      <div>
        <FieldLabel>Does your AI system ever approve its own proposals? <span className="text-red-400">*</span></FieldLabel>
        <RadioCards
          value={state.aiSelfApproval}
          onChange={(v) => update({ aiSelfApproval: v })}
          options={[
            { value: "no", label: "No", desc: "The AI proposes, humans review and approve" },
            { value: "unsure", label: "Unsure", desc: "We haven't mapped this part of the workflow yet" },
            { value: "yes", label: "Yes", desc: "The AI currently approves its own output in some cases" },
          ]}
        />
      </div>

      {state.aiSelfApproval === "yes" && (
        <div className="bg-amber-950 border border-amber-700 rounded-xl p-5">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
            <div>
              <div className="text-amber-300 font-semibold mb-2">Non-bypassable invariant</div>
              <p className="text-amber-200 text-sm leading-relaxed">
                CerbaSeal enforces that AI systems cannot authorize their own proposals. This is a hard rule that cannot be changed by policy, configuration, or override. If your current workflow allows self-authorization, CerbaSeal will <strong>REJECT</strong> those requests automatically. This is by design — it is the core governance guarantee CerbaSeal provides.
              </p>
              <p className="text-amber-300 text-sm mt-3 font-medium">
                Your workflow will need to separate the proposing actor (AI) from the approving actor (human) before deployment.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Step 4: Approvers ────────────────────────────────────────────────────────

function Step4({ state, update }: { state: WizardState; update: (p: Partial<WizardState>) => void }) {
  function updateApprover(i: number, patch: Partial<Approver>) {
    const next = state.approvers.map((a, idx) => (idx === i ? { ...a, ...patch } : a));
    update({ approvers: next });
  }

  function addApprover() {
    update({ approvers: [...state.approvers, { clientRoleName: "", authorityClass: "" }] });
  }

  function removeApprover(i: number) {
    if (state.approvers.length > 1) {
      update({ approvers: state.approvers.filter((_, idx) => idx !== i) });
    }
  }

  return (
    <div className="space-y-5">
      <div className="bg-slate-800/50 border border-slate-700 rounded-lg p-4 text-sm text-slate-300">
        Who in your organization has the authority to approve AI-proposed actions? Map each role name to the closest CerbaSeal authority class.
      </div>

      {state.approvers.map((approver, i) => (
        <div key={i} className="bg-slate-900 border border-slate-700 rounded-xl p-5">
          <div className="flex items-center justify-between mb-4">
            <span className="text-white font-medium text-sm">Approver role {i + 1}</span>
            {state.approvers.length > 1 && (
              <button
                type="button"
                onClick={() => removeApprover(i)}
                className="text-slate-500 hover:text-red-400 transition-colors"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            )}
          </div>

          <div className="space-y-4">
            <div>
              <FieldLabel>Role name in your organization <span className="text-red-400">*</span></FieldLabel>
              <TextInput
                value={approver.clientRoleName}
                onChange={(v) => updateApprover(i, { clientRoleName: v })}
                placeholder="e.g. Senior Fraud Analyst"
              />
            </div>

            <div>
              <FieldLabel>CerbaSeal authority class <span className="text-red-400">*</span></FieldLabel>
              <div className="space-y-2">
                {AUTHORITY_CLASSES.map((cls) => (
                  <button
                    key={cls.value}
                    type="button"
                    onClick={() => updateApprover(i, { authorityClass: cls.value })}
                    className={`w-full text-left px-4 py-3 rounded-lg border text-sm transition-all ${
                      approver.authorityClass === cls.value
                        ? "border-blue-500 bg-blue-950"
                        : "border-slate-700 bg-slate-800 hover:border-slate-600"
                    }`}
                  >
                    <div className={`font-medium ${approver.authorityClass === cls.value ? "text-blue-300" : "text-white"}`}>
                      <code className="text-xs mr-2">{cls.value}</code>{cls.label}
                    </div>
                    <div className="text-xs text-slate-400 mt-0.5">{cls.desc}</div>
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>
      ))}

      <button
        type="button"
        onClick={addApprover}
        className="w-full border border-dashed border-slate-600 rounded-xl py-3 text-slate-400 hover:text-slate-300 hover:border-slate-500 transition-colors text-sm flex items-center justify-center gap-2"
      >
        <Plus className="w-4 h-4" /> Add another approver role
      </button>
    </div>
  );
}

// ─── Step 5: Deployment Mode ──────────────────────────────────────────────────

function Step5({ state, update }: { state: WizardState; update: (p: Partial<WizardState>) => void }) {
  const modes = [
    {
      value: "mode_a",
      label: "Mode A — Lamont Labs-hosted",
      desc: "CerbaSeal runs on Lamont Labs infrastructure. Lamont Labs manages uptime, updates, and the environment. Your team integrates via API. Minimal setup effort. Data residency is Lamont Labs default region.",
      setup: "Minimal",
      residency: "Lamont Labs region",
      who: "Lamont Labs",
    },
    {
      value: "mode_b",
      label: "Mode B — Partner-hosted",
      desc: "CerbaSeal is deployed and managed by a certified consulting partner. The partner handles infrastructure and updates. Your team works with the partner for configuration and support escalation.",
      setup: "Low (partner manages)",
      residency: "Partner infrastructure",
      who: "Certified partner",
    },
    {
      value: "mode_c",
      label: "Mode C — Client-controlled",
      desc: "CerbaSeal runs on your own infrastructure. Your technical team owns deployment, updates, monitoring, and infrastructure. Full control over data residency. Requires Node.js 18+ and pnpm.",
      setup: "Higher (self-managed)",
      residency: "Your infrastructure",
      who: "Your team",
    },
  ];

  return (
    <div className="space-y-4">
      <p className="text-slate-400 text-sm">Select where CerbaSeal will run for this pilot.</p>

      {modes.map((mode) => (
        <button
          key={mode.value}
          type="button"
          onClick={() => update({ deploymentMode: mode.value })}
          className={`w-full text-left rounded-xl border p-5 transition-all ${
            state.deploymentMode === mode.value
              ? "border-blue-500 bg-blue-950/40"
              : "border-slate-700 bg-slate-900 hover:border-slate-600"
          }`}
        >
          <div className={`font-semibold text-sm mb-2 ${state.deploymentMode === mode.value ? "text-blue-300" : "text-white"}`}>
            {mode.label}
          </div>
          <p className="text-slate-400 text-sm leading-relaxed mb-3">{mode.desc}</p>
          <div className="flex gap-4 text-xs text-slate-500">
            <span>Setup effort: <span className="text-slate-300">{mode.setup}</span></span>
            <span>Data residency: <span className="text-slate-300">{mode.residency}</span></span>
            <span>Managed by: <span className="text-slate-300">{mode.who}</span></span>
          </div>
        </button>
      ))}
    </div>
  );
}

// ─── Step 6: Summary + Download ───────────────────────────────────────────────

function Step6({ state }: { state: WizardState }) {
  const [downloading, setDownloading] = useState(false);
  const [downloaded, setDownloaded] = useState(false);

  async function handleDownload() {
    setDownloading(true);
    try {
      await downloadConfigPackage(state);
      setDownloaded(true);
    } finally {
      setDownloading(false);
    }
  }

  const workflowClass = toSnakeCase(state.workflowName) || "unnamed_workflow";

  return (
    <div className="space-y-5">
      <p className="text-slate-400 text-sm">Review your configuration before generating the package.</p>

      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
        <SummarySection title="Workflow">
          <SummaryRow label="Name" value={state.workflowName || "—"} />
          <SummaryRow label="Class" value={workflowClass} mono />
          <SummaryRow label="Description" value={state.workflowDescription || "—"} />
          <SummaryRow label="Frequency" value={state.workflowFrequency || "—"} />
          <SummaryRow label="Environment" value={state.workflowEnvironment || "—"} />
          <SummaryRow label="Sector" value={state.workflowSector || "—"} />
        </SummarySection>

        <SummarySection title="Actions">
          {state.actions.filter((a) => a.name).length === 0 ? (
            <p className="text-slate-500 text-sm">No actions configured</p>
          ) : (
            state.actions.filter((a) => a.name).map((a, i) => (
              <div key={i} className="text-sm">
                <span className="text-white font-medium">{a.name}</span>
                <code className="text-blue-400 text-xs ml-2">{toSnakeCase(a.name)}</code>
                <span className="text-slate-400 text-xs ml-2">
                  {a.consequential ? "consequential" : "informational"} · {a.reversible === "yes" ? "reversible" : a.reversible === "no" ? "irreversible" : "partially reversible"}
                </span>
                <span className={`text-xs ml-2 font-medium ${a.consequential ? "text-amber-400" : "text-emerald-400"}`}>
                  → {a.consequential ? "requires_approval" : "auto_allow"}
                </span>
              </div>
            ))
          )}
        </SummarySection>

        <SummarySection title="AI System">
          <SummaryRow label="Output" value={state.aiOutput || "—"} />
          <SummaryRow label="Model" value={state.aiModel || "—"} />
          <SummaryRow label="Hosting" value={state.aiHosting || "—"} />
          <SummaryRow
            label="Self-approval"
            value={state.aiSelfApproval === "yes" ? "⚠️ Yes (CerbaSeal will REJECT)" : state.aiSelfApproval || "—"}
          />
        </SummarySection>

        <SummarySection title="Approvers">
          {state.approvers.filter((ap) => ap.clientRoleName && ap.authorityClass).length === 0 ? (
            <p className="text-slate-500 text-sm">No approvers configured</p>
          ) : (
            state.approvers.filter((ap) => ap.clientRoleName && ap.authorityClass).map((ap, i) => (
              <div key={i} className="text-sm">
                <span className="text-white">{ap.clientRoleName}</span>
                <span className="text-slate-400 mx-2">→</span>
                <code className="text-blue-400 text-xs">{ap.authorityClass}</code>
              </div>
            ))
          )}
        </SummarySection>

        <SummarySection title="Deployment">
          <SummaryRow
            label="Mode"
            value={
              state.deploymentMode === "mode_a"
                ? "Mode A — Lamont Labs-hosted"
                : state.deploymentMode === "mode_b"
                ? "Mode B — Partner-hosted"
                : state.deploymentMode === "mode_c"
                ? "Mode C — Client-controlled"
                : "—"
            }
          />
        </SummarySection>
      </div>

      <div className="bg-slate-900 border border-blue-900 rounded-xl p-4">
        <div className="text-blue-400 text-xs font-bold mb-2 tracking-wide">PACKAGE CONTENTS</div>
        <div className="space-y-1.5">
          {[
            { file: "cerbaseal.policy.json", desc: "Policy configuration — place at repository root" },
            { file: "pilot-checklist.md", desc: "Deployment and verification checklist" },
            { file: "scenario-tests.ts", desc: "Runnable TypeScript test scenarios" },
            { file: "handoff-pack.md", desc: "Summary for your technical owner" },
          ].map(({ file, desc }) => (
            <div key={file} className="flex items-start gap-2 text-sm">
              <CheckCircle className="w-3.5 h-3.5 text-blue-400 mt-0.5 flex-shrink-0" />
              <div>
                <code className="text-blue-300 text-xs">{file}</code>
                <span className="text-slate-400 text-xs ml-2">— {desc}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      <Button
        onClick={handleDownload}
        disabled={downloading}
        className="w-full bg-blue-600 hover:bg-blue-500 text-white py-3 text-base font-semibold disabled:opacity-60"
      >
        {downloading ? (
          "Generating…"
        ) : downloaded ? (
          <>
            <CheckCircle className="w-5 h-5 mr-2" /> Package downloaded — generate again
          </>
        ) : (
          <>
            <Download className="w-5 h-5 mr-2" /> Generate Configuration Package
          </>
        )}
      </Button>

      {downloaded && (
        <p className="text-emerald-400 text-sm text-center">
          Download complete. Place <code className="text-emerald-300">cerbaseal.policy.json</code> at the repository root and run <code className="text-emerald-300">pnpm audit:repo</code> to verify.
        </p>
      )}
    </div>
  );
}

function SummarySection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="text-slate-500 text-xs font-bold tracking-wide mb-2 uppercase">{title}</div>
      <div className="space-y-1.5">{children}</div>
    </div>
  );
}

function SummaryRow({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex gap-3 text-sm">
      <span className="text-slate-500 w-28 flex-shrink-0">{label}</span>
      {mono ? (
        <code className="text-blue-400 text-xs">{value}</code>
      ) : (
        <span className="text-slate-200">{value}</span>
      )}
    </div>
  );
}

// ─── Validation ───────────────────────────────────────────────────────────────

function validateStep(step: number, state: WizardState): string | null {
  if (step === 1) {
    if (!state.workflowName.trim()) return "Workflow name is required.";
    if (!state.workflowDescription.trim()) return "Workflow description is required.";
    if (!state.workflowFrequency) return "Please select how often this workflow runs.";
    if (!state.workflowEnvironment) return "Please select the current status.";
    if (!state.workflowSector) return "Please select the industry or sector.";
  }
  if (step === 2) {
    if (!state.actions[0]?.name.trim()) return "At least one action with a name is required.";
    for (let i = 0; i < state.actions.length; i++) {
      if (state.actions[i].name && !state.actions[i].reversible) {
        return `Please specify if action ${i + 1} is reversible.`;
      }
    }
  }
  if (step === 3) {
    if (!state.aiOutput.trim()) return "Please describe what your AI system produces.";
    if (!state.aiHosting) return "Please select where the AI model is hosted.";
    if (!state.aiSelfApproval) return "Please answer the self-approval question.";
  }
  if (step === 4) {
    if (!state.approvers[0]?.clientRoleName.trim()) return "At least one approver role name is required.";
    if (!state.approvers[0]?.authorityClass) return "Please select a CerbaSeal authority class for the first approver.";
    for (let i = 0; i < state.approvers.length; i++) {
      if (state.approvers[i].clientRoleName && !state.approvers[i].authorityClass) {
        return `Please select an authority class for approver ${i + 1}.`;
      }
    }
  }
  if (step === 5) {
    if (!state.deploymentMode) return "Please select a deployment mode.";
  }
  return null;
}

// ─── Wizard shell ─────────────────────────────────────────────────────────────

const STEP_LABELS = [
  "Workflow",
  "Actions",
  "AI Role",
  "Approvers",
  "Deployment",
  "Summary",
];

export default function Wizard() {
  const [step, setStep] = useState(1);
  const [state, setState] = useState<WizardState>(INITIAL_STATE);
  const [error, setError] = useState<string | null>(null);

  function update(patch: Partial<WizardState>) {
    setState((s) => ({ ...s, ...patch }));
    setError(null);
  }

  function next() {
    const err = validateStep(step, state);
    if (err) {
      setError(err);
      return;
    }
    setError(null);
    setStep((s) => Math.min(6, s + 1));
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  function back() {
    setError(null);
    setStep((s) => Math.max(1, s - 1));
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  const progress = ((step - 1) / 5) * 100;

  return (
    <main className="max-w-2xl mx-auto px-6 py-12">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <Wand2 className="w-6 h-6 text-violet-400" />
          <h1 className="text-2xl font-bold text-white">Workflow Mapping Wizard</h1>
        </div>
        <p className="text-slate-400 text-sm">
          6 steps · 30–60 minutes · generates a complete configuration package
        </p>
      </div>

      {/* Progress */}
      <div className="mb-8">
        <div className="flex items-center justify-between mb-2">
          <span className="text-slate-400 text-xs">
            Step {step} of 6 — {STEP_LABELS[step - 1]}
          </span>
          <span className="text-slate-500 text-xs">{Math.round(progress)}% complete</span>
        </div>
        <div className="w-full bg-slate-800 rounded-full h-1.5">
          <div
            className="bg-violet-500 h-1.5 rounded-full transition-all duration-300"
            style={{ width: `${progress}%` }}
          />
        </div>

        {/* Step dots */}
        <div className="flex gap-1 mt-3 justify-between">
          {STEP_LABELS.map((label, i) => {
            const n = i + 1;
            return (
              <button
                key={label}
                type="button"
                onClick={() => {
                  if (n < step) { setStep(n); setError(null); }
                }}
                disabled={n >= step}
                className={`flex flex-col items-center gap-1 group disabled:cursor-default`}
              >
                <div className={`w-2 h-2 rounded-full transition-colors ${
                  n < step ? "bg-violet-400" : n === step ? "bg-violet-500" : "bg-slate-700"
                }`} />
                <span className={`text-xs hidden sm:block ${
                  n === step ? "text-violet-400" : n < step ? "text-slate-400 group-hover:text-slate-300" : "text-slate-600"
                }`}>{label}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Step content */}
      <div className="mb-6">
        {step === 1 && <Step1 state={state} update={update} />}
        {step === 2 && <Step2 state={state} update={update} />}
        {step === 3 && <Step3 state={state} update={update} />}
        {step === 4 && <Step4 state={state} update={update} />}
        {step === 5 && <Step5 state={state} update={update} />}
        {step === 6 && <Step6 state={state} />}
      </div>

      {/* Error */}
      {error && (
        <div className="mb-4 bg-red-950 border border-red-700 rounded-lg px-4 py-3 text-red-300 text-sm flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 flex-shrink-0" />
          {error}
        </div>
      )}

      {/* Navigation */}
      <div className="flex justify-between">
        <Button
          type="button"
          onClick={back}
          disabled={step === 1}
          variant="outline"
          className="border-slate-700 text-slate-300 disabled:opacity-30"
        >
          <ChevronLeft className="w-4 h-4 mr-1" /> Back
        </Button>

        {step < 6 && (
          <Button
            type="button"
            onClick={next}
            className="bg-violet-600 hover:bg-violet-500 text-white"
          >
            Next <ChevronRight className="w-4 h-4 ml-1" />
          </Button>
        )}
      </div>
    </main>
  );
}
