export const REASON_CODES = {
  DECISION_ALLOWED: "DECISION_ALLOWED",
  DECISION_HELD: "DECISION_HELD",
  DECISION_REJECTED: "DECISION_REJECTED",

  NO_POLICY_PACK: "NO_POLICY_PACK",
  NO_PROVENANCE: "NO_PROVENANCE",
  REQUIRED_APPROVAL_MISSING: "REQUIRED_APPROVAL_MISSING",
  INVALID_APPROVAL_AUTHORITY: "INVALID_APPROVAL_AUTHORITY",
  PRIVILEGED_AUTH_NOT_SATISFIED: "PRIVILEGED_AUTH_NOT_SATISFIED",
  APPROVAL_SIGNATURE_MISSING: "APPROVAL_SIGNATURE_MISSING",
  LOGGING_NOT_READY: "LOGGING_NOT_READY",
  AI_CANNOT_AUTHORIZE: "AI_CANNOT_AUTHORIZE",
  PROHIBITED_USE: "PROHIBITED_USE",
  CONTROL_STALE_OR_INVALID: "CONTROL_STALE_OR_INVALID",
  TRUST_STATE_INVALID: "TRUST_STATE_INVALID",
  UNKNOWN_ACTION_CLASS: "UNKNOWN_ACTION_CLASS",
  MALFORMED_REQUEST: "MALFORMED_REQUEST",
  INVALID_PROPOSAL: "INVALID_PROPOSAL"
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
